/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;
import Menu.KONEKSI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author ASUS
 */


public class MenuReservasiHotel extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pet = null;
    ResultSet rs = null;
    Object set;
   int x=0;

    private String nama;
    private String tanggal;
    private float jenis;
    private String nomor;
    private float lama;
    private double tarif;
    private String telepon;
    private Object hasilKamar;
    private Object Nama;
   

    /**
     * Creates new form MenuReservasiHotel
     */
    public MenuReservasiHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hasilNama = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hasilTanggal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hasilJenis = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        hasilNomor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hasilHarga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        hasilTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnHasil = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setBackground(new java.awt.Color(242, 141, 165));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang di Mavan Hotels");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, 30));

        jLabel18.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jLabel18.setText("Silahkan lengkapi Data dibawah untuk Melakukan Booking Kamar Hotel");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 81, 469, 30));

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jButton2.setText("ADMIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Kamar Hotel :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel3.setText("1. Kamar Standar    200.000/Hari  Nomor Kamar Pilih 101,102,103");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 18));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel4.setText("2. Kamar Deluxe     275.000/Hari Nomor Kamar Pilih 104,105,201");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, 22));

        jLabel5.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel5.setText("3. Kamar Suite        300.000/Hari Nomor Kamar Pilih 202,203");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, 361, -1));

        jLabel6.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel6.setText("4. Kamar President 340.000/Hari Nomor Kamar Pilih 204,205");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 154, 361, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Langit-Mendung-Laeacco-Musim-Panas-Pantai-2-Kursi-Di-Bawah-Palm-Pohon-Fotografi-Latar-Belakang-Vinyl.jpg_Q90.jpg_.jpg"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 180));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 123, -1, -1));

        jLabel7.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Nama Pelanggan      :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 114, 35));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 325, 184, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 51));
        jLabel14.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Tanggal                     :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 120, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 364, 184, -1));

        jLabel8.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Pilih Jenis Kamar 1-4 :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 412, 184, -1));

        jLabel19.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Nomor Kamar             :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 459, 184, -1));

        jLabel16.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText(" Telepon                    :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 506, 184, -1));

        jLabel10.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel10.setText("Nama");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 62, -1));
        jPanel2.add(hasilNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 305, -1));

        jLabel15.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel15.setText("Tanggal");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 52, 29));

        hasilTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTanggalActionPerformed(evt);
            }
        });
        jPanel2.add(hasilTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 305, -1));

        jLabel11.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel11.setText("Jenis Kamar");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 71, -1));

        hasilJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilJenisActionPerformed(evt);
            }
        });
        jPanel2.add(hasilJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 305, -1));

        jLabel20.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel20.setText("Nomor Kamar");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, -1));

        hasilNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilNomorActionPerformed(evt);
            }
        });
        jPanel2.add(hasilNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 305, -1));

        jLabel12.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel12.setText("Harga Kamar");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 88, -1));
        jPanel2.add(hasilHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 305, -1));

        jLabel17.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel17.setText("Telepon");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 62, 22));
        jPanel2.add(hasilTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 305, -1));

        jLabel9.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Lama Menginap        :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 120, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 565, 184, -1));

        btnHasil.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        btnHasil.setText("Hasil");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });
        jPanel2.add(btnHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 633, -1, -1));

        btnHapus.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 633, -1, -1));

        jLabel13.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel13.setText("Total Bayar");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 71, 40));
        jPanel2.add(totalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 305, -1));

        jButton1.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 97, -1));

        tbData.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Tanggal", "Telepon", "Jenis", "Harga", "Nomor Kamar", "Total Bayar"
            }
        ));
        jScrollPane1.setViewportView(tbData);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 962, 157));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/35-350565_pool-resort-maldives-rose-gold-windows-laptop.jpg"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        // TODO add your handling code here:
        nama = String.valueOf(jTextField1.getText());
       tanggal = String.valueOf(jTextField5.getText());
       telepon = String.valueOf(jTextField6.getText());
        jenis = Float.parseFloat(jTextField2.getText());
        nomor = String.valueOf(jTextField7.getText());
        lama = Float.parseFloat(jTextField3.getText());
        hasilNama.setText(""+nama);
        hasilTanggal.setText(""+tanggal);
        hasilTelepon.setText(""+telepon);
        hasilNomor.setText(""+nomor);
        
        
        if(jenis == 1){
            
            hasilJenis.setText("Kamar Standar");
            hasilHarga.setText("Rp.200.000/hari");
            
        }else if(jenis == 2){
            
            hasilJenis.setText("Kamar Deluxe");
            hasilHarga.setText("Rp.275.000/hari");
        }else if(jenis == 3){
            
            hasilJenis.setText("Kamar Suite");
            hasilHarga.setText("Rp.300.000/hari");
        }else if(jenis == 4){
            
            hasilJenis.setText("Kamar president");
            hasilHarga.setText("Rp.340.000/hari");
        }
        
        if (jenis == 1){
            tarif = lama * 200000;
            totalBayar.setText("Rp." + tarif);
            
        }else if (jenis == 2){
            tarif = lama * 275000;
            totalBayar.setText("Rp." + tarif);
            
        }else if (jenis == 3){
            tarif = lama * 300000;
            totalBayar.setText("Rp." + tarif);
            
        }else if (jenis == 4){
            tarif = lama * 340000;
            totalBayar.setText("Rp." + tarif);
            
        }
     
    }//GEN-LAST:event_btnHasilActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
        jTextField6.setText("");
        hasilNama.setText("");
        hasilTanggal.setText("");
        hasilNomor.setText("");
        hasilTelepon.setText("");
        hasilHarga.setText("");
        hasilJenis.setText("");
        totalBayar.setText("");
         hasilNomor.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conn = KONEKSI.getkoneksi();
       String sql = "insert into reservasikamar values (?,?,?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, hasilNama.getText());
                stat.setString(2, hasilTanggal.getText());
                stat.setString(3, hasilJenis.getText());
                stat.setString(4, hasilNomor.getText());
                stat.setString(5, hasilHarga.getText());
                stat.setString(6, hasilTelepon.getText());
                stat.setString(7, totalBayar.getText());
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Booking Berhasil");
                
               
                
                
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Booking gagal" +e);
            }
         
        tbData.setValueAt(hasilNama.getText(),x,0);
        tbData.setValueAt(hasilTanggal.getText(),x,1);
        tbData.setValueAt(hasilTelepon.getText(),x,2);
        tbData.setValueAt(hasilJenis.getText(),x,3);
        tbData.setValueAt(hasilHarga.getText(),x,4);
        tbData.setValueAt(hasilNomor.getText(),x,5);
        tbData.setValueAt(totalBayar.getText(),x,6);
        x=x+1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hasilJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilJenisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login rg = new Login();
            rg.setVisible(true);
            rg.setLocationRelativeTo(null);
            rg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hasilTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTanggalActionPerformed

    private void hasilNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilNomorActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReservasiHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReservasiHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHasil;
    private javax.swing.JTextField hasilHarga;
    private javax.swing.JTextField hasilJenis;
    private javax.swing.JTextField hasilNama;
    private javax.swing.JTextField hasilNomor;
    private javax.swing.JTextField hasilTanggal;
    private javax.swing.JTextField hasilTelepon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables

   
        }
    

